exclude_patterns:
- "src/__tests__/"
- "config/"
- "src/index.js"
- "src/serviceWorker.js"
version: "2"         
checks:
  similar-code:
    config:
      threshold: 75
  identical-code:
    config:
      threshold: 75
