export const FETCH_AUTOMATION = 'FETCH_AUTOMATION';
export const FETCH_AUTOMATION_SUCCESS = 'FETCH_AUTOMATION_SUCCESS';
export const FETCH_AUTOMATION_FAILURE = 'FETCH_AUTOMATION_FAILURE';
export const FETCH_STATS_REQUEST = 'FETCH_STATS_REQUEST';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';
