export const FETCH_AUTOMATION_REQUEST = 'FETCH_AUTOMATION_REQUEST';
export const FETCH_AUTOMATION_SUCCESS = 'FETCH_AUTOMATION_SUCCESS';
export const FETCH_AUTOMATION_FAILURE = 'FETCH_AUTOMATION_FAILURE';
