export const FETCH_AUTOMATION = 'FETCH_AUTOMATION';
export const FETCH_AUTOMATION_SUCCESS = 'FETCH_AUTOMATION_SUCCESS';
export const FETCH_AUTOMATION_FAILURE = 'FETCH_AUTOMATION_FAILURE';
export const FETCH_STATS_REQUEST = 'FETCH_STATS_REQUEST';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';

// Retry automations
export const RETRY_AUTOMATION = 'RETRY_AUTOMATION';
export const RETRY_AUTOMATION_SUCCESS = 'RETRY_AUTOMATION_SUCCESS';
export const RETRY_AUTOMATION_FAILURE = 'RETRY_AUTOMATION_FAILURE';
export const SET_REAL_TIME_DATA = 'SET_REAL_TIME_DATA';
export const FETCH_REAL_TIME_DATA = 'FETCH_REAL_TIME_DATA';
export const RESET_REAL_TIME_DATA = 'RESET_REAL_TIME_DATA';
export const RESET_REAL_TIME_DATA_SUCCESS = 'RESET_REAL_TIME_DATA_SUCCESS';
